// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package referralgen

import (
	"database/sql"
	"time"
)

type Template struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Name      sql.NullString `json:"name"`
	Template  sql.NullString `json:"template"`
	Params    []string       `json:"params"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Fullname          string    `json:"fullname"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	CreatedAt         time.Time `json:"created_at"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
}
