// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package referralgen

import (
	"context"
)

type Querier interface {
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTemplateById(ctx context.Context, id int64) (Template, error)
	GetTemplateById(ctx context.Context, id int64) (Template, error)
	GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Template, error)
	GetTemplatesByUser(ctx context.Context, userID int64) ([]Template, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	UpdateTemplateById(ctx context.Context, arg UpdateTemplateByIdParams) (Template, error)
}

var _ Querier = (*Queries)(nil)
